### ISSUE TITLE
Latest version v.1.1.2 doesn't show device buttons

### ISSUE THREAD

**Issue by just-Nob** [fralik/Duorem#13]
After installing Dourem's latest version from F-Droid repo, the main screen stays empty: no bottoms to start / shut down the device, no status is displayed.
Anyway, the device (i.e. its settings) are still there - if you edit the device by tapping on the pencil icon, all settings are displayed!
But even if some details are changed and the new settings are saved, the main screen stays empty.
I also tried to re-enter the settings (by choosing "replace device" and automatic recognition), but the result remains unchanged.

**Comment by fralik** [comment]
Thanks for reporting it. I didn't change the code for the latest version, but did change the version of dependent libraries as I have difficulties compiling it.
What version of Android do you have?

**Comment by fralik** [comment]
OK. I see it on my device as well. Will work on the fix over the week-end.

**Comment by just-Nob** [comment]
Ok, thanks a lot.
Anyway, I'm running Oreo 8.1 on my device.

**Comment by twocoolbeans** [comment]
Was just about to report this. Can see everything in landscape mode. Portrait mode is the issue.

![demo](https://user-images.githubusercontent.com/26072479/40556827-1a40b7dc-601c-11e8-91c2-43540cf3fdc1.jpg)

![demo2](https://user-images.githubusercontent.com/26072479/40556842-27fead48-601c-11e8-8acb-f682f14b79bc.jpg)

**Comment by fralik** [comment]
Here is a similar problem: https://stackoverflow.com/questions/49912075/constraintlayout-1-1-0-different-from-1-0-2-is-it-a-bug

**Comment by fralik** [comment]
Fixed in 01befe0e327de9b2bea69cb1d0c06cba05347c9c. The fix appears in v1.1.3.
