### ISSUE TITLE
Refresh feature 

### ISSUE THREAD

**Issue by onos1** [fralik/Duorem#15]
After turned on or before, the refresh button doesn't work

**Comment by fralik** [comment]
What do you mean by 'refresh button'?

**Comment by onos1** [comment]
Sorry! I actually meant `restart`

**Comment by fralik** [comment]
Restart is not active if host is turned off (i.e. no connection to host, red circle is visible in front of the host name).
I will have to check the behaviour you describe as 'after turned on'. Note however that it can take some time for your host to boot (turn on). Until it is booted, the restart button will be inactive.

**Comment by fralik** [comment]
@onos1, Other thing I can think of: are you sure you have correct SSH parameters?

**Comment by onos1** [comment]
Issue figured, everything perfect now, thanks..

**Comment by fralik** [comment]
Great!
