### ISSUE TITLE
Support hostname

### ISSUE THREAD

**Issue by AeliusSaionji** [fralik/Duorem#16]
Given dynamic IP addresses, a remote control doesn't do much for me if I can't use a hostname :)

**Comment by fralik** [comment]
True. I've made an update. You may set IP address to 0.0.0.0. However the particular value is not important. The app will check if remote machine is accessible through ip address or hostname.

This is just the code. The app is not yet updated on F-Droid. If you know how to build Android apps, you can build it from the source code and start using the new functionality.
