### ISSUE TITLE
Missing shutdown timer 

### ISSUE THREAD

**Issue by cmburg** [fralik/Duorem#17]
I miss a timer to shutdown the host.

When the host is up and running the "shutdown" button could be resized (eg 45%ish) to make space for a new to add button "set timer" or any similar. After tapping the button a numberfield (to make the android keyboard automatically switch to the number layout) should appear with buttons to accept the value or to cancel. The rest of the implementation is considered to be quite easy since ssh is working for shutdown.

I see this feature as a large improvement of user experience since noone has to manually sah into the host (or just leave it running)

**Comment by fralik** [comment]
If you edit host details, there is "advanced details" at the bottom. If toggled, it will show you the shutdown command that is sent. You can modify it and specify the time delay there. [Here](https://askubuntu.com/questions/505929/shutdown-after-a-certain-time) you can find more details about the command.

As fot the change to the interface. I made Duorem specifically the way it is - with huge buttons and very little settings. So shrinking buttons and adding new functionality is something I will not implement. Sorry if this upsets you. You can fork the project and modify it to your needs.
