### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by antgustech** [fralik/Duorem#20]
Would be great with Android TV support so we can remote wake PCs running servers. I tried side loading this on my Nvidia Shield and it works but there are two issues:

1. The app doesn't show up in the launcher so you have to navigate to Settings>Apps and find it in the list of launch it. 

2. The background is white and text looks blurry.

**Comment by fralik** [comment]
1. How do yoy install it on TV? I guess it might be related.

2. Do you have specs of your TV? I've just run Duorem on TV emulator and it looks OK.

If I won't be able to reproduce these issues in the emulator, then I may ask you to test development builds on your hardware. I myself do not have an android TV.

**Comment by antgustech** [comment]
> 1. How do yoy install it on TV? I guess it might be related.
> 2. Do you have specs of your TV? I've just run Duorem on TV emulator and it looks OK.
> 
> If I won't be able to reproduce these issues in the emulator, then I may ask you to test development builds on your hardware. I myself do not have an android TV.

1 I downloaded APK from F-droid and put on USB stick. I then installed the APK from the USB stick on the Nvidia Shield TV. My tv is unrelevant seeing this is on the Nvidia Shield. :)

**Comment by fralik** [comment]
I see, but your TV (which acts as a screen for the shield) is 4K, isn't it?

I googled a bit and it seems that blur can appear on 4K screens.

**Comment by antgustech** [comment]
> I see, but your TV (which acts as a screen for the shield) is 4K, isn't it?
> 
> I googled a bit and it seems that blur can appear on 4K screens.

Yeah it's 4k. Honestly I don't mind that the text is blurry and white background. But it would be great if the app would show up in the launcher. As I said right now I have to navigate to the apps settings in order to launch it.

**Comment by fralik** [comment]
Fixed in  739c94c.
