### ISSUE TITLE
Release latest versoion as compiled APK?

### ISSUE THREAD

**Issue by antgustech** [fralik/Duorem#22]
Hi,

When is 1.1.4 being released as APK on F-Droid? :)

**Comment by fralik** [comment]
For some reason, the automatic updates are broken. I made the pull request https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6360, so it is now up to F-Droid maintainers. I hope it won't take much longer.

**Comment by antgustech** [comment]
Alright, thanks!

**Comment by fralik** [comment]
Closing it as v1.1.4 has been merged into F-Droid data.

**Comment by fralik** [comment]
Version 1.1.4 is now available from F-Droid.
