### ISSUE TITLE
German Translation welcome?

### ISSUE THREAD

**Issue by just-Nob** [fralik/Duorem#4]
Do you like to add translations?
I could do the German one, if you'd like to.
I guess, all strings to translate are located in "strings.xml"?

**Comment by fralik** [comment]
Sure! Yes, English is in app/src/main/res/values/strings.xml. You can translate it and attach the file here (just drop in the input field).

**Comment by just-Nob** [comment]
Ok, I'll do asap.
Anyway, please have a little patience. ;)

**Comment by fralik** [comment]
I am closing it due to inactivity.
