### ISSUE TITLE
State of Duorem's "Status LED" after the app's start

### ISSUE THREAD

**Issue by just-Nob** [fralik/Duorem#5]
When starting Duorem, the small "LED" left near the MAC-address showing the device's status is always green before getting the device's real state, even if the device is powered off.

It needs a few seconds before the status LED changes to the device's real state. This is something that might be a little confusing.

My suggestion is to "grey out" the LED as long as the device's state is unknown.

**Comment by fralik** [comment]
Indeed. I've fixed this, so that the status of remote device is checked earlier. This will be part of v1.1.0.
