### ISSUE TITLE
Switching applications reset all fields in "add new device"

### ISSUE THREAD

**Issue by MScMSc** [fralik/Duorem#9]
I try to add a new device manually. Since I cannot copy&paste the whole MAC address, I keep it open in another (notepad-like) app and start entering the numbers manually. However, when I switch to the notepad app and back, all fields I have so far filled out have been reset.

**Comment by fralik** [comment]
True. Will fix it soon (actually, have already fixed it, but it needs a bit of testing).

**Comment by fralik** [comment]
Fixed in 1c2c14ac. Will include in the next release.

**Comment by fralik** [comment]
Release 1.1.1 is out.
